before:
  hooks:
    - go mod download
builds:
- id: "fluitans"
  main: ./cmd/fluitans
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
dockers:
  -
    image_templates:
    - "ghcr.io/sargassum-eco/fluitans/{{ .ProjectName }}:latest"
    - "ghcr.io/sargassum-eco/fluitans/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/sargassum-eco/fluitans/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/sargassum-eco/fluitans/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
